mineshop/cart/urls.py
from django.conf.urls import url
from .views import *

#app_name = 'cart'
urlpatterns = [
         url(r'^$',cart_detail,name='cart_detail'),
         url(r'^add/(?P<product_id>\d+)/$',cart_add,name='cart_add'),
         url(r'^remove/(?P<product_id>\d+)/$',cart_remove,name='cart_remove')
    ]

mineshop/mineshop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from shop.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',index,name='product_list'),
    url(r'cart/',include('cart.urls',namespace='cart')),
    url(r'^category/(\w+)/$',product_category,name='cate'),
    url(r'^detail/(\d+)/(\w+)/$',detail,name='detail')
]+ static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

mineshop/cart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mineshop/shop/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Categories(models.Model):
    name=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100)

    def __unicode__(self):
        return self.name

class Product(models.Model):
    category=models.ForeignKey(Categories)
    name=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100,null=True)
    #image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    pic = models.FileField(upload_to = 'pic',null=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    
    def __unicode__(self):
        return self.name
    

    

mineshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

mineshop/shop/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

mineshop/cart/views.py
from django.shortcuts import *
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import *
from django.http import *
from django.core.urlresolvers import reverse


# Create your views here.
@require_POST
def cart_add(request,product_id):
    cart= Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = CartForm(request.POST)
    if form.is_valid():
        cd=form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],
                 update_quantity=cd['update'])
        
    return redirect('cart:cart_detail')   

def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    #product = get_object_or_404(Product,id=d)

    for item in cart:
        
        item['update_quantity_form'] = CartForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    
    return render(request,'cart/detail.html',{'cart':cart})
    '''
    for item in cart:
        if item['product']==product:
            cart_product=item
    form = CartForm(initial={'quantity':cart_product['quantity'],
                             'update':True})
    return render(request,'cart/detail.html',{'cart_product':cart_product,
                                         'form':form,
                                         'product':product})
    '''
    

mineshop/shop/views.py
from django.shortcuts import *
from .models import *
# Create your views here.
from cart.forms import *
from cart.cart import Cart

def index(request):
    cat=Categories.objects.all()

    for i in cat:
        for k in i.product_set.all():
            print (k.name)
            
    return render(request,'home.html',{'cat':cat})

def product_category(request,n):
    all_prod=Categories.objects.get(slug=n)
    categories=Categories.objects.all()
    return render(request,'product_cat.html',{'cat':all_prod,'categories':categories})

def detail(request,d,slug):
    cart=Cart(request)
    #product=Product.objects.get(slug=slug)
    product = get_object_or_404(Product, id=d, slug=slug)
    if request.method=='POST':
        cartform=CartForm(request.POST)
        if cartform.is_valid():
            cd=cartform.cleaned_data
            cart.add(product=product,quantity=cd['quantity'],
                 update_quantity=cd['update'])

            return redirect('cart:cart_detail')

    else:
        cartform=CartForm()
        
    return render(request,'detail.html',{'prod':product,'cartform':cartform})

mineshop/cart/templates/cart/detail.html
{% load app_tags %}
<html>
<head>
<link rel="stylesheet" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/base.css">

<style>
#subheader {
    background:#ececec;
    color:#444;
	margin-top:10px;
    padding:5px 100px;
    overflow:auto;
}
#subheader .cart {
    float:right;
    padding-top:0px;
}
</style>
</head>
<body>
<div id="subheader" style="padding-right:50">
        <div class="cart">
		
		{% with total_items=cart|cart_len %}
                {% if cart|length > 0 %}
				 
                    <p>{{total_items}} items in cart </p> 
                {% else %}
				    <p>cart is empty</p>
                {% endif %}
            {% endwith %}		
        </div>
    </div>
	
<h2 style="margin-top:80px;margin-left:200px;">Your Shopping bag</h2>
<div style="width:800px;margin-top:10px;margin-left:200px;">
<table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>                
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
         {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="">
                        <img src="{% if product.pic %}{{ product.pic.url }}{% endif %}" width="100px" height="100px">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
				
                <td><a href="{% url "cart:cart_remove" product.id %}"><span class="glyphicon glyphicon-trash"></span></a></td>
                
				<td class="num">Rs&nbsp;{{ item.price }}</td>
                <td class="num">Rs&nbsp;{{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">Rs&nbsp;{{ cart.get_total_price }}</td>
        </tr>
           </tbody>
    </table>
	
	 <p class="text-right">
	                 
        <a href="{% url "product_list" %}" class="btn btn-primary btn-md">Continue shopping</a>
      
		<a href="" class="btn btn-primary btn-md">Buy</a>
    </p>
	</div>
</body>
</html>

mineshop/shop/templates/detail.html
<html>
<head>

<link rel="stylesheet" href="/static/css/bootstrap.min.css">
 
 <style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 200px;
    background-color: #f1f1f1;
}

li a {
    display: block;
    color: #000;
    padding: 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: #4CAF50;
    color: white;
	text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
	text-decoration: none;
}


#subheader {
    background:#ececec;
    color:#444;
	margin-top:10px;
    padding:5px 100px;
    overflow:auto;
}
#subheader .cart {
    float:right;
    padding-top:0px;
}
</style>
</head>
<body>


 <div id="subheader" style="padding-right:50">
        <div class="cart">
		
		{% with total_items=cart|length %}
                {% if cart|length > 0 %}
				 
                    <p>{{total_items}} items in cart </p> 
                {% else %}
				    <p>cart is empty</p>
                {% endif %}
            {% endwith %}		
        </div>
    </div>
	
<div style="float:left;margin-left:100px">
<h1>{{ prod.name }}</h1>
<table>
<tr><td>
<img src="{% if prod.pic %}{{ prod.pic.url }}{% endif %}" width="200px" height="200px">
        
</td>		
<td>
       
        <p>Rs {{ prod.price }}</p>
		 <p>description:{{ prod.description }}</p>
		 
</td>		

		 
		

</tr>
</table>
<div style="margin-left:150px;">
<form action="" method="post">
         {% csrf_token %}
		{{cartform.as_table}}
		 <input type="submit" value="Add to cart">
		</form>
</div>
</div>




</body>

</html>

mineshop/shop/templates/home.html
{% load app_tags %}
<html>
<head>

<link rel="stylesheet" href="/static/css/bootstrap.min.css">
 
 <style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 200px;
    background-color: #f1f1f1;
}

li a {
    display: block;
    color: #000;
    padding: 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: #4CAF50;
    color: white;
	text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
	text-decoration: none;
}

#subheader {
    background:#ececec;
    color:#444;
	margin-top:10px;
    padding:5px 100px;
    overflow:auto;
}
#subheader .cart {
    float:right;
    padding-top:0px;
}
</style>
</head>
<body>

 <div id="subheader" style="padding-right:50">
        <div class="cart">
		
		{% with total_items=cart|length %}
                {% if cart|length > 0 %}
				 
                    <p>{{total_items}} items in cart </p> 
                {% else %}
				    <p>cart is empty</p>
                {% endif %}
            {% endwith %}		
        </div>
    </div>
	
<h2 style="margin-top:50px;margin-left:300px;">List of products</h2>
<div style="float:left;margin-left:30px;margin-top:10px;">
<ul>
  <li><a class="active" href="#home">All</a></li>
  {% for i in cat %}
  <li><a href="{% url 'cate' i.slug %}">{{i.name}}</a></li>
  {% endfor %}
  
</ul>
</div>
{% for i in cat %}
<div style="width:800px;margin-left:250px">
{% for k in i.product_set.all %}

<div style="width:200px;float:left;margin-left:50px;margin-top:20px;">
<img src='{{k.pic.url}}' width="150px" height="150px"/>
<p style="margin-left:25%;">{{k.name}}</p><br>
 <a style="margin-left:15%;" href="{% url 'detail' k.id k.slug %}" class="btn btn-primary btn-md">Add To Cart</a>
</div>
			
{% endfor %}
	
</div>

{% endfor %}




</body>

</html>

mineshop/shop/templates/product_cat.html
{% load app_tags %}
<html>
<head>

<link rel="stylesheet" href="/static/css/bootstrap.min.css">
 
 <style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 200px;
    background-color: #f1f1f1;
}

li a {
    display: block;
    color: #000;
    padding: 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: #4CAF50;
    color: white;
	text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
	text-decoration: none;
}


#subheader {
    background:#ececec;
    color:#444;
	margin-top:10px;
    padding:5px 100px;
    overflow:auto;
}
#subheader .cart {
    float:right;
    padding-top:0px;
}
</style>
</head>
<body>

<div id="subheader" style="padding-right:50">
        <div class="cart">
		
		{% with total_items=cart|cart_len %}
                {% if cart|length > 0 %}
				 
                    <p>{{total_items}} items in cart </p> 
                {% else %}
				    <p>cart is empty</p>
                {% endif %}
            {% endwith %}		
        </div>
    </div>
	
<h2 style="margin-top:50px;margin-left:300px;">List of products</h2>
<div style="float:left;margin-left:30px;margin-top:10px;">
<ul>
  <li><a href="/">All</a></li>
  {% for i in categories %}
  <li><a {% if cat.slug == i.slug %}class="active"{% endif %} href="{% url 'cate' i.slug %}">{{i.name}}</a></li>
  {% endfor %}
  
</ul>
</div>

<div style="width:800px;margin-left:250px">
{% for k in cat.product_set.all %}

<div style="width:200px;float:left;margin-left:50px;margin-top:20px;">
<img src='{{k.pic.url}}' width="150px" height="150px"/>
<p style="margin-left:25%;">{{k.name}}</p><br>
 <a style="margin-left:15%;" href="{% url 'detail' k.id k.slug %}" class="btn btn-primary btn-md">Add To Cart</a>
</div>
			
{% endfor %}
	
</div>





</body>

</html>