session_middleware/chap2/chap1/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('myapp.urls',namespace='myapp',app_name='myapp'))
    
]

session_middleware/chap2/myapp/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$',post_list,name='post_list'),
    #url(r'^$',PostListView.as_view(),name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',post_detail,name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$',post_share,name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$',post_list,name='post_list_by_tag')
    ]

session_middleware/chap2/myapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES =(('draft','draft'),('published','published'))

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,related_name='blog_posts')
    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    objects = models.Manager()
    published = PublishedManager()

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myapp:post_detail',args=[self.publish.year,
                                                self.publish.strftime('%m'),
                                                self.publish.strftime('%d'),
                                                self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        
    def __unicode__(self):
        return 'Comment by {} on {}'.format(self.name,self.post)






    

session_middleware/chap2/myapp/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False , widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields = ('name','email','body')

session_middleware/chap2/myapp/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.

from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from .models import Post,Comment
from django.core.mail import send_mail
from .forms import EmailPostForm ,CommentForm
from taggit.models import Tag
from django.db.models import Count


def post_list(request,tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
        
    paginator = Paginator(object_list,3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,'list.html',{'page':page,
                                                 'posts':posts,'tag':tag})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by =3
    template_name='list.html'

def post_detail(request,year,month,day,post):
    post = get_object_or_404(Post,slug=post,
                                  status='published',
                                  publish__year=year,
                                  publish__month=month,
                                  publish__day=day,
                                 )
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():

            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    else:
        comment_form = CommentForm()

    # list of similar posts
    post_tags_ids = post.tags.values_list('id',flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    
    return render(request,'detail.html',{'post':post,'comments':comments,
                                          'comment_form':comment_form,'similar_posts':similar_posts})
    

def post_share(request,post_id):
    post = get_object_or_404(Post,id=post_id,status='published')
    sent=False

    if request.method=='POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}" '.format(cd['name'],cd['email'],post.title)
            message = 'Read "{}" at {} comments:{}'.format(post.title,post_url,cd['comments'])
            send_mail(subject,message,'vin1989eet@gmail.com',[cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request,'share.html',{'post':post,'form':form,'sent':sent})    

session_middleware/chap2/myapp/templates/detail.html
{% extends "myapp/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{post.title}}</h1>
<p><Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|linebreaks }}

<p><a href="{% url "myapp:post_share" post.id %}">Share this post</a></p>   
    
	  <h2>Similar posts </h2>
	   {% for post in similar_posts %}
	   <p>
	      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
	</p>
        {% empty %}
          There are no similar posts yet.
        {% endfor %}		  



   {% with comments.count as total_comments %}
    <h2>
	 {{ total_comments }} comment {{ total_comments|pluralize }}
	 </h2>
   {% endwith %}

   {% for comment in comments %}
    <div class="comment">
	   <p class="info">
	     Comment {{ forloop.counter }} by {{ comment.name }}
		   {{ comment.created }}
	  </p>
         {{ comment.body|linebreaks }}
     </div>
     {% empty %}
        <p>There are no comments yet..</p>
    {% endfor %}

       {% if new_comment %}
          <h2>Your comment has been added.</h2>
        {% else %}
         <h2>Add a new comment</h2>
    
         <form action="." method="post">
		     {{ comment_form.as_p }}
			  {% csrf_token %}
		    <p><input type='submit' value="Add comment"></p>
         </form>

        {% endif %}		 
        	
{% endblock %}

session_middleware/chap2/myapp/templates/list.html
<!--
With the tag template tag, we are telling Django to inherit from the
blog/base.html template. Then we are filing the title and content blocks of the
base template with content.

-->

{% extends 'myapp/base.html' %}

{% block title %}My blog {% endblock %}

{% block content %}
  <h1>My blog</h1>
  
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  
  {% for post in posts %}
   <h2>
     <a href="{{ post.get_absolute_url }}" >{{post.title}}</a>
	 </h2>
	 
	 <p class="tags">
	  Tags:
	   {% for tag in post.tags.all %}
	   <a href="{% url "myapp:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
	   {% if not forloop.last %}, {% endif %}
	   {% endfor %}
	   
	   
	 <p>Published  {{post.publish}} by {{ post.author }}</p>
	 {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}

{% include "pagination.html" with page=posts %}

<!--in case of PostViewList use,page=page_obj-->
  
{% endblock %}


 
 
  

session_middleware/chap2/myapp/templates/myapp/base.html
{% load staticfiles %}

<!--
this tag  tells Django to load the staticfiles template tags
that are provided by the django.contrib.staticfiles application. After loading
it, you are able to use the static   template fiter throughout this template.
-->

<!--

 there are two block  tags. These tell Django that we want to
define a block in that area. 

-->
<html>
<head>
   <title>{% block title %}{% endblock %}</title>
   <link href="{% static 'css/blog.css' %}" rel='stylesheet'>
   </head>
   
<body>
<div id='content'>
   {% block content %}
    {% endblock %}
</div>

</body>
</html>

session_middleware/chap2/myapp/templates/pagination.html
<div class="pagination">
 <span class="step-links">
 {% if page.has_previous %}
 <a href="?page={{ page.previous_page_number }}">Previous</a>
 {% endif %}
 <span class="current">
 Page {{ page.number }} of {{ page.paginator.num_pages }}.
 </span>
 {% if page.has_next %}
 <a href="?page={{ page.next_page_number }}">Next</a>
 {% endif %}
 </span>
</div>

session_middleware/chap2/myapp/templates/share.html
{% extends "myapp/base.html" %}
{% block title %}share a post{% endblock %}

{% block content %}
    {% if sent %}
	 <h1>E-mail successfully sent </h1>
	 <p>
	  "{{ post.title }}" was successfully sent to {{ cd.to }}
	  </p>
	{% else %}
      <h1> Share "{{ post.title }}" by email</h1>
    <form action="." method="post">
	{% csrf_token %}
      {{ form.as_p}}	
	<input type="submit" value="send e-mail">
     </form>
     {% endif %}
    {% endblock %}	 